# Generated by Django 4.2.6 on 2023-12-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='year',
            field=models.CharField(max_length=30),
        ),
    ]
