# Generated by Django 4.2.6 on 2023-12-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0002_alter_mobile_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
